### ISSUE TITLE
core::function_traits<T>::argument<N> always return a type of the 1st argument

### ISSUE THREAD

**Issue by snizovtsev** [mnmlstc/core#40]
Test case:

```cpp
#include <type_traits>
#include <core/functional.hpp>

struct A {};
struct B {};
struct C {};

typedef A(*foo)(B,C);

static_assert( std::is_same< core::function_traits<foo>::argument<0>, B >::value, "arg0 != B" );
static_assert( std::is_same< core::function_traits<foo>::argument<1>, C >::value, "arg1 != C" ); // fails
```

Tested on Apple clang-700.1.76 and Homebrew gcc 5.2.0 at OS X.

**Comment by slurps-mad-rips** [comment]
Hi.

What version of Core are you using?

**Comment by slurps-mad-rips** [comment]
Oh never mind. Find the issue. This is a cause of the latest commit (the refactor that added a meta namespace).

If you look at the definition of [function_traits::argument](https://github.com/mnmlstc/core/blob/master/include/core/functional.hpp#L53), you'll see that I am accidentally ignoring the N parameter. If need be feel free to replace the 0 with an N until I have the fix pushed up.

Thanks for your bug report! :D!
