### ISSUE TITLE
Compile error when constructing any with const T* (clang / Mac OS X)

### ISSUE THREAD

**Issue by EvanBalster** [mnmlstc/core#60]
Hello Izzy!!  :D

`core::v2::any` issues a compiler error when the constructor for a parameter of constant pointer type is used.  This can be reproduced by attempting to wrap a pointer to a `const int`:

```cpp
const int x = 5;
core::v2::any container(&x);
```

`reinterpret_cast from 'core::v2::impl::data_type*' (aka void**) to 'core::v2::impl::dispatch<const MyType*, true>' (aka const MyType**) casts away qualifiers.`

I'm using Clang on a slightly outdated Xcode and using this library to aid in compatibility with old versions of Mac OS X.

**Comment by bruxisma** [comment]
Hey Evan!

Just so you know, this library isn't under development anymore, for reasons I can't go into right now 😅. However, I'm fairly certain you won't see this pop up if you do `core::v2::any const container(&x)`. 

That said, you might get better experience by forking the implementation to fix it. 🙂

**Comment by EvanBalster** [comment]
The issue occurred with `core::v2::any` but I'm sure any old pointer wrapper class would work fine as a workaround.  I was able to work around the problem in my application, so no sweat!
